version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - spring.kafka.bootstrap-servers=kafka:9092
      - spring.data.mongodb.uri=mongodb://mongo:27017/purchase
    depends_on:
      - kafka
      - mongo
    networks:
      - app-network

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - spring.data.mongodb.uri=mongodb://mongo:27017/purchase
    depends_on:
      - kafka
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge