version: '3.8'

services:
  stockdb:
    image: "postgres:13"  # Use the official PostgreSQL image
    restart: always
    environment:
      POSTGRES_DB: '${DB_DATABASE}'         # Name of the database to be created
      POSTGRES_USER: '${DB_USER}'           # PostgreSQL user
      POSTGRES_PASSWORD: '${DB_PASSWORD}'   # Password for PostgreSQL user
    ports:
      - '5432:5432'  # Expose PostgreSQL port
    volumes:
      - ./db:/docker-entrypoint-initdb.d   # Optional: Initialize database from scripts in ./db folder
      - stock-data:/var/lib/postgresql/data  # Data persistence volume
    networks:
      - stock-network

  stockapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://stockdb:${DB_PORT}/${DB_DATABASE}
      - spring.datasource.username=${DB_USER}
      - spring.datasource.password=${DB_PASSWORD}
    depends_on:
      - stockdb
    networks:
      - stock-network
    links:
      - stockdb

networks:
  stock-network:
    driver: bridge

volumes:
  stock-data:
    driver: local